* GPS convert
This shiny app is used to convert GPS coordinates. Currently the code only supports RT90,
SWEREF99TM, WGS84 and UTM32N. It will import a file that holds the gps coordinates (currently supports .xls, .xlsx, .odf, .csv, .txt and .tdf. The last two assumes a tab delimeted file. After specifying the columns with coordinate data and name the app will convert values and generate 
a simple map showing the coordinates on a map. 

If you want to try this code you need to install the following packages.

#+BEGIN_SRC R
  install.packages(c("shiny","DT","tidyverse",
                     "readxl","leaflet", "rgdal"))

#+END_SRC

Depending on environment used there are sometimes not possible to install rgdal as above and you need 
install gdal outside R. On mac os x you can solve the problem by installing gdal via brew.

#+BEGIN_SRC sh
brew install gdal

#+END_SRC

On Linux based system one can install gdal via package managers. If using apt-get the following will do

#+BEGIN_SRC sh
sudo apt-get install libgdal1-dev libproj-dev

#+END_SRC

and on fedora one can try

#+BEGIN_SRC sh
sudo dnf install rgdal expat proj

#+END_SRC

if it fails you will normally get a readable error message from dnf 


After this you can launch the app with

#+BEGIN_SRC R
shiny::runGitHub("GPS-Convert", "CGI-NRM")

#+END_SRC

Note that this procedure requires an active internet connection at
launch.

You can also download the app and just open the app.R file in r-studio
and just press the "Run app" to start it. If prefer to run it outside
r-studio just copy the app.R code and paste it to your r-session to
launch the web app.

The current version of the app is running on a free tier session at shinyapps.io and can hence be tested before you install.
